routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

// Home route goes here
Route::get('/', 'HomeController@index')->name('home');

// User routes go here
Route::get('dashboard', 'User\UserController@index')->name('dashboard');
Route::put('users/{user}', 'User\UserController@update')->name('users.update');
Route::put('users-psw-update', 'User\UserController@updatePassword')->name('user.password.update');
Route::put('users-upload-image', 'User\UserController@uploadImage')->name('users.image.upload');
Route::delete('users/{user}', 'User\UserController@destroy')->name('users.destroy');
Route::post('addresses', 'AddressController@store')->name('addresses.store');
Route::put('addresses/{address}', 'AddressController@update')->name('addresses.update');
Route::delete('addresses/{address}', 'AddressController@destroy')->name('addresses.destroy');

// Calculation route goes here
Route::get('calculate', 'SiteController@calculate')->name('calculate');
Route::get('address', 'SiteController@address')->name('address.get');
Route::get('payment', 'SiteController@payment')->name('payment');
Route::get('order/complete', 'SiteController@orderSuccess')->name('order.success');
Route::get('order/invoice', 'SiteController@orderInvoice')->name('order.invoice');

// Courier routes go here
Route::get('couriers', 'CarrierController@filter')->name('couriers.show');

// Order routes go here
Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');

// Admin routes go here
Route::prefix('secure/administrator/')->group(function () {
    Route::get('admins', 'Admin\AdminController@admins')->name('admins.index');
    Route::get('admins/create', 'Admin\AdminController@create')->name('admins.create');
    Route::post('admins', 'Admin\AdminController@store')->name('admins.store');
    Route::get('admins/{admin}/edit', 'Admin\AdminController@edit')->name('admins.edit');
    Route::put('admins/{admin}', 'Admin\AdminController@update')->name('admins.update');
    Route::delete('admins/{admin}', 'Admin\AdminController@destroy')->name('admins.destroy');
    Route::get('admin/dashboard', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::get('admin/settings', 'Admin\AdminController@settings')->name('admin.settings');
    Route::put('admin/email/update', 'Admin\AdminController@updateEmail')->name('admin.email.update');
    Route::put('admin/password/reset', 'Admin\AdminController@updatePassword')->name('admin.password.reset');
    Route::put('admin/account/update/{admin}', 'Admin\AdminController@updateAdmin')->name('admin.account.update');
    Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'Admin\Auth\LoginController@login');
    Route::post('admin/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

    // User routes go here
    Route::get('users', 'User\UserController@users')->name('users');
    Route::get('users/{user}', 'User\UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'User\UserController@edit')->name('users.edit');
    Route::put('users-update/{user}', 'User\UserController@updateUsers')->name('users.profile.update');

    // Role routes go here
    Route::resource('roles', 'Admin\RoleController');

    // Custom pages routes go here
    Route::resource('pages', 'PageController');

    // Type routes go here
    Route::resource('types', 'TypeController');

    // Invoice routes go here
    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::post('invoices', 'InvoiceController@store')->name('invoices.store');
    Route::get('invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::delete('invoices/{invoice}', 'InvoiceController@destroy')->name('invoices.destroy');

    // Order routes go here
    Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');
    Route::resource('orders', 'OrderController');

    // Rate routes go here
    Route::resource('rates', 'RateController');

    // Courier routes go here
    Route::get('carriers/download', function () {
        return Excel::download(new \App\Exports\CarrierExport, 'carriers.xlsx');
    })->name('carriers.download')->middleware('auth:admin');
    Route::resource('carriers', 'CarrierController');
});

// Custom page route goes here
Route::get('/{slug}', 'PageController@slug')->name('page.show');

app/Rate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rate extends Model
{
    /**
     * Get the type that owns the rate.
     */
    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    /**
     * Get the carrier that owns the rate.
     */
    public function carrier()
    {
        return $this->belongsTo('App\Carrier');
    }
}

app/Http/Controllers/RateController.php
<?php

namespace App\Http\Controllers;

use App\Rate;
use App\Type;
use App\Carrier;
use Illuminate\Http\Request;

class RateController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rates = Rate::all()->sortByDesc('id');

        return view('admin.rate.rates', compact('rates'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Get all couriers
        $carriers = Carrier::all()->sortByDesc('id');

        // Get all couriers
        $types = Type::all()->sortByDesc('id');

        return view('admin.rate.rate-create-edit', compact('carriers', 'types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate form data
        $request->validate([
            'distance_from' => 'required|numeric|min:0',
            'distance_to' => 'required|numeric|min:0|gte:distance_from',
            'weight_from' => 'required|numeric|min:0',
            'weight_to' => 'required|numeric|min:0|gte:weight_from',
            'length_from' => 'required|numeric|min:0',
            'length_to' => 'required|numeric|min:0|gte:length_from',
            'width_from' => 'required|numeric|min:0',
            'width_to' => 'required|numeric|min:0|gte:width_from',
            'height_from' => 'required|numeric|min:0',
            'height_to' => 'required|numeric|min:0|gte:height_from',
            'price' => 'required|numeric|gt:0',
            'type_id' => 'required|integer',
            'carrier_id' => 'required|integer',
        ]);

        // Create a model instance assign form data & save to DB
        $rate = new Rate();
        $rate->distance_from = $request->distance_from;
        $rate->distance_to = $request->distance_to;
        $rate->weight_from = $request->weight_from;
        $rate->weight_to = $request->weight_to;
        $rate->length_from = $request->length_from;
        $rate->length_to = $request->length_to;
        $rate->width_from = $request->width_from;
        $rate->width_to = $request->width_to;
        $rate->height_from = $request->height_from;
        $rate->height_to = $request->height_to;
        $rate->price = $request->price;
        $rate->type_id = $request->type_id;
        $rate->carrier_id = $request->carrier_id;
        $rate->save();

        return redirect()->back()->with('success', 'Rate created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function show(Rate $rate)
    {
        // Get the model
        $rate = Rate::find($rate->id);

        return view('admin.rate.rate-show', compact('rate'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function edit(Rate $rate)
    {
        // Get all couriers
        $carriers = Carrier::all()->sortByDesc('id');

        // Get all couriers
        $types = Type::all()->sortByDesc('id');

        // Get the model
        $rate = Rate::find($rate->id);

        $edit = true;

        return view('admin.rate.rate-create-edit', compact('rate', 'carriers', 'types', 'edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Rate $rate)
    {
        // Validate form data
        $request->validate([
            'distance_from' => 'required|numeric|min:0',
            'distance_to' => 'required|numeric|min:0|gte:distance_from',
            'weight_from' => 'required|numeric|min:0',
            'weight_to' => 'required|numeric|min:0|gte:weight_from',
            'length_from' => 'required|numeric|min:0',
            'length_to' => 'required|numeric|min:0|gte:length_from',
            'width_from' => 'required|numeric|min:0',
            'width_to' => 'required|numeric|min:0|gte:width_from',
            'height_from' => 'required|numeric|min:0',
            'height_to' => 'required|numeric|min:0|gte:height_from',
            'price' => 'required|numeric|gt:0',
            'type_id' => 'required|integer',
            'carrier_id' => 'required|integer',
        ]);

        // Get the model assign form data & save to DB
        $rate = Rate::find($rate->id);
        $rate->distance_from = $request->distance_from;
        $rate->distance_to = $request->distance_to;
        $rate->weight_from = $request->weight_from;
        $rate->weight_to = $request->weight_to;
        $rate->length_from = $request->length_from;
        $rate->length_to = $request->length_to;
        $rate->width_from = $request->width_from;
        $rate->width_to = $request->width_to;
        $rate->height_from = $request->height_from;
        $rate->height_to = $request->height_to;
        $rate->price = $request->price;
        $rate->type_id = $request->type_id;
        $rate->carrier_id = $request->carrier_id;
        $rate->save();

        return redirect()->back()->with('success', 'Rate updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rate $rate)
    {
        // Get the model
        Rate::destroy($rate->id);

        return redirect()->back()->with('success', 'Rate deleted successfully.');
    }
}

resources/views/admin/rate/rate-show.blade.php
@extends('admin.layouts.app')

@section('title')
    Rate show
@endsection

@section('heading')
    Rate show
@endsection

@section('breadcrumb')
    Rate show
@endsection

@section('content')
    <!-- Row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header bg-info">
                    <h4 class="mb-0 text-white">Form with view only</h4>
                </div>
                <form class="form-horizontal">
                    <div class="form-body">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-10">
                                    <h4 class="card-title">Rate show</h4>
                                </div>
                                <div class="col-md-2 text-right">
                                    <a href="{{ route('rates.index') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                                </div>
                            </div>
                        </div>
                        <hr class="mt-0 mb-5">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Courier:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->carrier->title }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Type:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->type->title }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                            </div>
                            <!--/row-->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Distance range:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->distance_from }} - {{ $rate->distance_to }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Weight range:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->weight_from }} - {{ $rate->weight_to }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                            </div>
                            <!--/row-->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Length range:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->length_from }} - {{ $rate->length_to }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Width range:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->width_from }} - {{ $rate->width_to }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                            </div>
                            <!--/row-->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Height range:</label>
                                        <div class="col-md-9">
                                            <p class="form-control-static"> {{ $rate->height_from }} - {{ $rate->height_to }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Price:</label>
                                        <div class="col-md-9">
                                        <p class="form-control-static">€ {{ $rate->price }} </p>
                                        </div>
                                    </div>
                                </div>
                                <!--/span-->
                            </div>
                            <!--/row-->
                        </div>
                        <hr>
                        <div class="form-actions">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-offset-3 col-md-9">
                                                <a href="{{ route('rates.edit', $rate->id)}}" class="btn btn-danger"> <i class="fa fa-pencil"></i> Edit</a>
                                                <a href="{{ route('rates.index') }}" class="btn btn-dark">Cancel</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6"> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Row -->
@endsection

resources/views/admin/rate/rates.blade.php
@extends('admin.layouts.app')

@section('title')
    Rates
@endsection

@section('heading')
    Rates
@endsection

@section('breadcrumb')
    Rates
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! html_entity_decode(Session::get('success')) !!}
        </div>
    @endif
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">Rates</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('rates.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-hover border display" style="width: 100%">
                            <thead>
                            <tr>
                                <th>Courier</th>
                                <th>Type</th>
                                <th>Distance range</th>
                                <th>Weight range</th>
                                <th>Length range</th>
                                <th>Width range</th>
                                <th>Height range</th>
                                <th>Price</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rates as $rate)
                                <tr>
                                    <td>{{ $rate->carrier->title }}</td>
                                    <td>{{ $rate->type->title }}</td>
                                    <td>{{ $rate->distance_from }} - {{ $rate->distance_to }}</td>
                                    <td>{{ $rate->weight_from }} - {{ $rate->weight_to }}</td>
                                    <td>{{ $rate->length_from }} - {{ $rate->length_to }}</td>
                                    <td>{{ $rate->width_from }} - {{ $rate->width_to }}</td>
                                    <td>{{ $rate->height_from }} - {{ $rate->height_to }}</td>
                                    <td>€ {{ $rate->price }}</td>
                                    <td>
                                        <form action="{{ route('rates.destroy', $rate->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('rates.show', $rate->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                            <a href="{{ route('rates.edit', $rate->id)}}" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i> </a>
                                            <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection