routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

// Home route goes here
Route::get('/', 'HomeController@index')->name('home');

// User routes go here
Route::get('dashboard', 'User\UserController@index')->name('dashboard');
Route::put('users/{user}', 'User\UserController@update')->name('users.update');
Route::put('users-psw-update', 'User\UserController@updatePassword')->name('user.password.update');
Route::put('users-upload-image', 'User\UserController@uploadImage')->name('users.image.upload');
Route::delete('users/{user}', 'User\UserController@destroy')->name('users.destroy');
Route::post('addresses', 'AddressController@store')->name('addresses.store');
Route::put('addresses/{address}', 'AddressController@update')->name('addresses.update');
Route::delete('addresses/{address}', 'AddressController@destroy')->name('addresses.destroy');

// Calculation route goes here
Route::get('calculate', 'SiteController@calculate')->name('calculate');
Route::get('address', 'SiteController@address')->name('address.get');
Route::get('payment', 'SiteController@payment')->name('payment');
Route::get('order/complete', 'SiteController@orderSuccess')->name('order.success');
Route::get('order/invoice', 'SiteController@orderInvoice')->name('order.invoice');

// Courier routes go here
Route::get('couriers', 'CarrierController@filter')->name('couriers.show');

// Order routes go here
Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');

// Admin routes go here
Route::prefix('secure/administrator/')->group(function () {
    Route::get('admins', 'Admin\AdminController@admins')->name('admins.index');
    Route::get('admins/create', 'Admin\AdminController@create')->name('admins.create');
    Route::post('admins', 'Admin\AdminController@store')->name('admins.store');
    Route::get('admins/{admin}/edit', 'Admin\AdminController@edit')->name('admins.edit');
    Route::put('admins/{admin}', 'Admin\AdminController@update')->name('admins.update');
    Route::delete('admins/{admin}', 'Admin\AdminController@destroy')->name('admins.destroy');
    Route::get('admin/dashboard', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::get('admin/settings', 'Admin\AdminController@settings')->name('admin.settings');
    Route::put('admin/email/update', 'Admin\AdminController@updateEmail')->name('admin.email.update');
    Route::put('admin/password/reset', 'Admin\AdminController@updatePassword')->name('admin.password.reset');
    Route::put('admin/account/update/{admin}', 'Admin\AdminController@updateAdmin')->name('admin.account.update');
    Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'Admin\Auth\LoginController@login');
    Route::post('admin/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

    // User routes go here
    Route::get('users', 'User\UserController@users')->name('users');
    Route::get('users/{user}', 'User\UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'User\UserController@edit')->name('users.edit');
    Route::put('users-update/{user}', 'User\UserController@updateUsers')->name('users.profile.update');

    // Role routes go here
    Route::resource('roles', 'Admin\RoleController');

    // Custom pages routes go here
    Route::resource('pages', 'PageController');

    // Type routes go here
    Route::resource('types', 'TypeController');

    // Invoice routes go here
    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::post('invoices', 'InvoiceController@store')->name('invoices.store');
    Route::get('invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::delete('invoices/{invoice}', 'InvoiceController@destroy')->name('invoices.destroy');

    // Order routes go here
    Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');
    Route::resource('orders', 'OrderController');

    // Rate routes go here
    Route::resource('rates', 'RateController');

    // Courier routes go here
    Route::get('carriers/download', function () {
        return Excel::download(new \App\Exports\CarrierExport, 'carriers.xlsx');
    })->name('carriers.download')->middleware('auth:admin');
    Route::resource('carriers', 'CarrierController');
});

// Custom page route goes here
Route::get('/{slug}', 'PageController@slug')->name('page.show');

resources/views/admin/page/page-create-edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Page create
@endsection

@section('heading')
    Page @if(isset($edit)) edit @else create @endif
@endsection

@section('breadcrumb')
    Page @if(isset($edit)) edit @else create @endif
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! html_entity_decode(Session::get('success')) !!}
        </div>
    @endif
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">@if(isset($edit)) Edit @else Create @endif page</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('pages.index') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <form method="post" action="@if(isset($edit)) {{ route('pages.update', $page->id) }} @else {{ route('pages.store') }} @endif" novalidate enctype="multipart/form-data">
                        @csrf
                        @if(isset($edit))
                            @method('PUT')
                        @endif
                        <div class="row">
                            <div class="col-lg-12 col-md-12">

                                <div class="form-group validate">
                                    <h5>Title<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="title" value="@if(isset($edit)){{ $page->title }}@else{!! old('title') !!}@endif" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group validate">
                                    <h5>Content<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <textarea  name="content" class="form-control{{ $errors->has('content') ? ' is-invalid' : '' }} summernote" required data-validation-required-message="This field is required">@if(isset($edit)){{ $page->content }}@else{!! old('content') !!}@endif</textarea>
                                        @error('content')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group validate">
                                    <h5>Url<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">{{ url('/').'/' }}</div>
                                            </div>
                                            <input type="text" name="slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required" value="@if(isset($edit)){{ $page->slug }}@else{!! old('slug') !!}@endif">
                                        </div>
                                        @error('slug')
                                        <span class="invalid-feedback" role="alert" style="display: block">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group validate">
                                    <h5>Showcase Page<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <fieldset>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" name="status" value="1" required="" id="showcase1" class="custom-control-input" aria-invalid="false" @if(isset($edit)) @if($page->status === 1) checked @endif @endif>
                                                <label class="custom-control-label" for="showcase1">Active</label>
                                            </div>
                                        </fieldset>
                                        <fieldset>
                                            <div class="custom-control custom-radio">
                                                <input type="radio"  name="status" value="0" id="showcase" class="custom-control-input" aria-invalid="false" @if(isset($edit)) @if($page->status === 0) checked @endif @endif>
                                                <label class="custom-control-label" for="showcase">Inactive</label>
                                            </div>
                                            @error('status')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </fieldset>
                                        <div class="help-block"></div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-12">
                                        <hr>
                                    </div>
                                    <div class="col-md-10">
                                        <h4 class="card-title">SEO</h4>
                                    </div>
                                    <div class="col-md-2 text-right">

                                    </div>
                                    <div class="col-12">
                                        <hr>
                                    </div>
                                </div>

                                <div class="form-group validate">
                                    <h5>Meta Title<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="meta_title" value="@if(isset($edit)){{ $page->meta_title }}@else{!! old('meta_title') !!}@endif" class="form-control{{ $errors->has('meta_title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                        @error('meta_title')
                                        <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group validate">
                                    <h5>Meta Description<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <textarea  name="meta_description" class="form-control{{ $errors->has('meta_description') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">@if(isset($edit)){{ $page->meta_description }}@else{!! old('meta_description') !!}@endif</textarea>
                                        @error('meta_description')
                                        <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                            </div>

                            <div class="col-lg-12 col-md-12">
                                <hr>
                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info">Submit</button>
                                    <button type="reset" class="btn btn-inverse">Reset</button>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('.summernote').summernote({
            height: 300, // set editor height
            minHeight: null, // set minimum height of editor
            maxHeight: null, // set maximum height of editor
            focus: false // set focus to editable area after initializing summernote
        });
    </script>
@endsection

resources/views/admin/page/page-show.blade.php
@extends('admin.layouts.app')

@section('title')
    Page show
@endsection

@section('heading')
    Page show
@endsection

@section('breadcrumb')
    Page show
@endsection

@section('content')
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">{{ $page->title }}</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('pages.index') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    {!! html_entity_decode($page->content) !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/page/pages.blade.php
@extends('admin.layouts.app')

@section('title')
  Pages
@endsection

@section('heading')
    Pages
@endsection

@section('breadcrumb')
    Pages
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! html_entity_decode(Session::get('success')) !!}
        </div>
    @endif
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">Pages</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('pages.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-hover border display" style="width: 100%">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Content</th>
                                <th>Slug</th>
                                <th>Url</th>
                                <th>Meta title</th>
                                <th>Meta description</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($pages as $page)
                                <tr>
                                    <td>{{ $page->title }}</td>
                                    <td width="30%">{{ substr(strip_tags($page->content), 0, 375) }}.....</td>
                                    <td>{{ $page->slug }}</td>
                                    <td>{{ url($page->slug) }}</td>
                                    <td>{{ $page->meta_title }}</td>
                                    <td>{{ $page->meta_description }}</td>
                                    <td>
                                        @if($page->status === 1)
                                            <button type="button" class="btn waves-effect waves-light btn-rounded btn-success">Active</button>
                                        @else
                                            <button type="button" class="btn waves-effect waves-light btn-rounded btn-danger">Inactive</button>
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('pages.destroy', $page->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('pages.show', $page->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                            <a href="{{ route('pages.edit', $page->id)}}" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i> </a>
                                            <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection