routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

// Home route goes here
Route::get('/', 'HomeController@index')->name('home');

// User routes go here
Route::get('dashboard', 'User\UserController@index')->name('dashboard');
Route::put('users/{user}', 'User\UserController@update')->name('users.update');
Route::put('users-psw-update', 'User\UserController@updatePassword')->name('user.password.update');
Route::put('users-upload-image', 'User\UserController@uploadImage')->name('users.image.upload');
Route::delete('users/{user}', 'User\UserController@destroy')->name('users.destroy');
Route::post('addresses', 'AddressController@store')->name('addresses.store');
Route::put('addresses/{address}', 'AddressController@update')->name('addresses.update');
Route::delete('addresses/{address}', 'AddressController@destroy')->name('addresses.destroy');

// Calculation route goes here
Route::get('calculate', 'SiteController@calculate')->name('calculate');
Route::get('address', 'SiteController@address')->name('address.get');
Route::get('payment', 'SiteController@payment')->name('payment');
Route::get('order/complete', 'SiteController@orderSuccess')->name('order.success');
Route::get('order/invoice', 'SiteController@orderInvoice')->name('order.invoice');

// Courier routes go here
Route::get('couriers', 'CarrierController@filter')->name('couriers.show');

// Order routes go here
Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');

// Admin routes go here
Route::prefix('secure/administrator/')->group(function () {
    Route::get('admins', 'Admin\AdminController@admins')->name('admins.index');
    Route::get('admins/create', 'Admin\AdminController@create')->name('admins.create');
    Route::post('admins', 'Admin\AdminController@store')->name('admins.store');
    Route::get('admins/{admin}/edit', 'Admin\AdminController@edit')->name('admins.edit');
    Route::put('admins/{admin}', 'Admin\AdminController@update')->name('admins.update');
    Route::delete('admins/{admin}', 'Admin\AdminController@destroy')->name('admins.destroy');
    Route::get('admin/dashboard', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::get('admin/settings', 'Admin\AdminController@settings')->name('admin.settings');
    Route::put('admin/email/update', 'Admin\AdminController@updateEmail')->name('admin.email.update');
    Route::put('admin/password/reset', 'Admin\AdminController@updatePassword')->name('admin.password.reset');
    Route::put('admin/account/update/{admin}', 'Admin\AdminController@updateAdmin')->name('admin.account.update');
    Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'Admin\Auth\LoginController@login');
    Route::post('admin/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

    // User routes go here
    Route::get('users', 'User\UserController@users')->name('users');
    Route::get('users/{user}', 'User\UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'User\UserController@edit')->name('users.edit');
    Route::put('users-update/{user}', 'User\UserController@updateUsers')->name('users.profile.update');

    // Role routes go here
    Route::resource('roles', 'Admin\RoleController');

    // Custom pages routes go here
    Route::resource('pages', 'PageController');

    // Type routes go here
    Route::resource('types', 'TypeController');

    // Invoice routes go here
    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::post('invoices', 'InvoiceController@store')->name('invoices.store');
    Route::get('invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::delete('invoices/{invoice}', 'InvoiceController@destroy')->name('invoices.destroy');

    // Order routes go here
    Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');
    Route::resource('orders', 'OrderController');

    // Rate routes go here
    Route::resource('rates', 'RateController');

    // Courier routes go here
    Route::get('carriers/download', function () {
        return Excel::download(new \App\Exports\CarrierExport, 'carriers.xlsx');
    })->name('carriers.download')->middleware('auth:admin');
    Route::resource('carriers', 'CarrierController');
});

// Custom page route goes here
Route::get('/{slug}', 'PageController@slug')->name('page.show');

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Type;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::all()->sortByDesc('id');

        return view('admin.type.types', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.type.type-create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate form data
        $request->validate([
            'title' => 'required|string|max:255',
        ]);

        // Create a model instance assign form data & save to DB
        $type = new Type();
        $type->title = $request->title;
        $type->save();

        return redirect()->back()->with('success', 'Type created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        // Get the model
        $type = Type::find($type->id);

        return view('admin.type.type-show', compact('type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit(Type $type)
    {
        // Get the model
        $type = Type::find($type->id);
        $edit = true;

        return view('admin.type.type-create-edit', compact('type', 'edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Type $type)
    {
        // Validate form data
        $request->validate([
            'title' => 'required|string|max:255',
        ]);

        // Create a model instance assign form data & save to DB
        $type = Type::find($type->id);
        $type->title = $request->title;
        $type->save();

        return redirect()->back()->with('success', 'Type updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy(Type $type)
    {
        // Get the model
        Type::destroy($type->id);

        return redirect()->back()->with('success', 'Type deleted successfully.');
    }
}

resources/views/admin/type/type-create-edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Type create
@endsection

@section('heading')
    Type @if(isset($edit)) edit @else create @endif
@endsection

@section('breadcrumb')
    Type @if(isset($edit)) edit @else create @endif
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! html_entity_decode(Session::get('success')) !!}
        </div>
    @endif
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">@if(isset($edit)) Edit @else Create @endif type</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('types.index') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <form method="post" action="@if(isset($edit)) {{ route('types.update', $type->id) }} @else {{ route('types.store') }} @endif" novalidate enctype="multipart/form-data">
                        @csrf
                        @if(isset($edit))
                            @method('PUT')
                        @endif
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <h5>Title<span class="text-danger">*</span></h5>
                                    <div class="controls">
                                        <input type="text" name="title" value="@if(isset($edit)){{ $type->title }}@else{{ old('title') }}@endif" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                        @error ('title')
                                        <div class="invalid-tooltip">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12 col-md-12">
                                <hr>
                                <div class="text-xs-right">
                                    <button type="submit" class="btn btn-info">Submit</button>
                                    <button type="reset" class="btn btn-inverse">Reset</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/type/type-show.blade.php
@extends('admin.layouts.app')

@section('title')
    Type show
@endsection

@section('heading')
    Type show
@endsection

@section('breadcrumb')
    Type show
@endsection

@section('content')
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">Type</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('types.index') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="file_export" class="table table-striped table-hover border display" style="width: 100%">
                            <tbody>
                                <tr>
                                    <th>Title</th>
                                    <td>{{ $type->title }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/type/types.blade.php
@extends('admin.layouts.app')

@section('title')
    Types
@endsection

@section('heading')
    Types
@endsection

@section('breadcrumb')
    Types
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {!! html_entity_decode(Session::get('success')) !!}
        </div>
    @endif
    <!-- Row created callback -->
    <div class="row">
        <div class="col-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">Types</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('types.create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-hover border display" style="width: 100%">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($types as $type)
                                <tr>
                                    <td>{{ $type->title }}</td>
                                    <td>
                                        <form action="{{ route('types.destroy', $type->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('types.show', $type->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                            <a href="{{ route('types.edit', $type->id)}}" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i> </a>
                                            <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection