routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

// Home route goes here
Route::get('/', 'HomeController@index')->name('home');

// User routes go here
Route::get('dashboard', 'User\UserController@index')->name('dashboard');
Route::put('users/{user}', 'User\UserController@update')->name('users.update');
Route::put('users-psw-update', 'User\UserController@updatePassword')->name('user.password.update');
Route::put('users-upload-image', 'User\UserController@uploadImage')->name('users.image.upload');
Route::delete('users/{user}', 'User\UserController@destroy')->name('users.destroy');
Route::post('addresses', 'AddressController@store')->name('addresses.store');
Route::put('addresses/{address}', 'AddressController@update')->name('addresses.update');
Route::delete('addresses/{address}', 'AddressController@destroy')->name('addresses.destroy');

// Calculation route goes here
Route::get('calculate', 'SiteController@calculate')->name('calculate');
Route::get('address', 'SiteController@address')->name('address.get');
Route::get('payment', 'SiteController@payment')->name('payment');
Route::get('order/complete', 'SiteController@orderSuccess')->name('order.success');
Route::get('order/invoice', 'SiteController@orderInvoice')->name('order.invoice');

// Courier routes go here
Route::get('couriers', 'CarrierController@filter')->name('couriers.show');

// Order routes go here
Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');

// Admin routes go here
Route::prefix('secure/administrator/')->group(function () {
    Route::get('admins', 'Admin\AdminController@admins')->name('admins.index');
    Route::get('admins/create', 'Admin\AdminController@create')->name('admins.create');
    Route::post('admins', 'Admin\AdminController@store')->name('admins.store');
    Route::get('admins/{admin}/edit', 'Admin\AdminController@edit')->name('admins.edit');
    Route::put('admins/{admin}', 'Admin\AdminController@update')->name('admins.update');
    Route::delete('admins/{admin}', 'Admin\AdminController@destroy')->name('admins.destroy');
    Route::get('admin/dashboard', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::get('admin/settings', 'Admin\AdminController@settings')->name('admin.settings');
    Route::put('admin/email/update', 'Admin\AdminController@updateEmail')->name('admin.email.update');
    Route::put('admin/password/reset', 'Admin\AdminController@updatePassword')->name('admin.password.reset');
    Route::put('admin/account/update/{admin}', 'Admin\AdminController@updateAdmin')->name('admin.account.update');
    Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'Admin\Auth\LoginController@login');
    Route::post('admin/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

    // User routes go here
    Route::get('users', 'User\UserController@users')->name('users');
    Route::get('users/{user}', 'User\UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'User\UserController@edit')->name('users.edit');
    Route::put('users-update/{user}', 'User\UserController@updateUsers')->name('users.profile.update');

    // Role routes go here
    Route::resource('roles', 'Admin\RoleController');

    // Custom pages routes go here
    Route::resource('pages', 'PageController');

    // Type routes go here
    Route::resource('types', 'TypeController');

    // Invoice routes go here
    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::post('invoices', 'InvoiceController@store')->name('invoices.store');
    Route::get('invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::delete('invoices/{invoice}', 'InvoiceController@destroy')->name('invoices.destroy');

    // Order routes go here
    Route::get('orders/complete', 'OrderController@complete')->name('orders.complete');
    Route::resource('orders', 'OrderController');

    // Rate routes go here
    Route::resource('rates', 'RateController');

    // Courier routes go here
    Route::get('carriers/download', function () {
        return Excel::download(new \App\Exports\CarrierExport, 'carriers.xlsx');
    })->name('carriers.download')->middleware('auth:admin');
    Route::resource('carriers', 'CarrierController');
});

// Custom page route goes here
Route::get('/{slug}', 'PageController@slug')->name('page.show');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the address record associated with the client.
     */
    public function addresses()
    {
        return $this->hasMany('App\Address');
    }

    /**
     * Get the order record associated with the client.
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('verified')->except('users', 'updateUsers', 'show', 'edit');
        $this->middleware('auth:admin')->only('users', 'updateUsers', 'show', 'edit');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        // Get all users
        $user = User::find(auth()->user()->id);
        $addresses = json_encode($user->addresses);

        return view('user.dashboard', compact('user', 'addresses'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function users()
    {
        // Get all users
        $clients = User::all()->sortByDesc('id');

        return view('admin.user.users', compact('clients'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        // Find the model
        $user = User::find($user->id);

        return view('admin.user.user-show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // Find the model
        $user = User::find($user->id);

        return view('admin.user.user-edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        // Validate form data
        $rules = array(
            'name' => 'required|string|max:255',
            'address' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'country' => 'required|string|max:255',
            'state' => 'required|string|max:255',
            'phone' => 'required|string|max:255',
            'zipCode' => 'required|integer',
        );
        $validator = Validator::make ( $request->all(), $rules);

        if ($validator->fails()){
            return response()->json(array('errors'=> $validator->getMessageBag()->toarray()));
        }

        // Find the model
        $user = User::find($user->id);
        $user->name = $request->name;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->country = $request->country;
        $user->state = $request->state;
        $user->zipCode = $request->zipCode;
        $user->phone = $request->phone;
        $user->save();

        return response()->json($user);
    }

    /**
     * Update client password.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function updatePassword(Request $request)
    {
        // Validate form data
        $rules = array(
            'password' => 'required|string|min:8',
            'new_password' => 'required|string|min:8|confirmed',
        );
        $validator = Validator::make ( $request->all(), $rules);

        if ($validator->fails()){
            return response()->json(array('errors' => $validator->getMessageBag()->toarray()));
        }

        // Get the client
        $client = User::find(auth()->user()->id);
        if (!Hash::check($request->password, $client->password)){
            // Return json response
            return response()->json(['errors' => ['error' => 'Your old password did not match!']]);
        }

        // Upadate password
        $client->password = Hash::make($request->new_password);
        $client->save();

        // Return json response
        return response()->json();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User  $user)
    {
        // Remove the specified resource from storage
        User::destroy($user->id);

        return redirect()->back()->with('success', '<strong>Client</strong> deleted successfully.');
    }

    /**
     * Upload client image.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function uploadImage(Request $request)
    {
        // Validate form data
        $rules = array(
            'avatar' => 'required|image',
        );
        $validator = Validator::make ( $request->all(), $rules);

        if ($validator->fails()){
            return response()->json(array('errors' => $validator->getMessageBag()->toarray()));
        }

        // Get the client
        $client = User::find(auth()->user()->id);

        // Upload image
        if ($request->hasFile('avatar')) {
            //get filename with extension
            $filenamewithextension = $request->file('avatar')->getClientOriginalName();

            //get filename without extension
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);

            //get file extension
            $extension = $request->file('avatar')->getClientOriginalExtension();

            //filename to store
            $filenametostore = $filename.'_'.time().'.'.$extension;

            //Upload File
            $request->file('avatar')->storeAs('public/images/profile_images/thumbnail', $filenametostore);

            //Resize image here
            $thumbnailpath = public_path('storage/images/profile_images/thumbnail/'.$filenametostore);
            $img = Image::make($thumbnailpath)->resize(100, 100, function($constraint) {
                $constraint->aspectRatio();
            });
            $img->save($thumbnailpath);

            // Delete previous image from directory
            if ($client->avatar) {
                Storage::delete('public/images/profile_images/thumbnail/'.$client->avatar);
            }
        }

        $client->avatar = $filenametostore;
        $client->save();

        // Return json response
        return response()->json($filenametostore);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function updateUsers(Request $request, User $user)
    {
        // Validate form data
        $request->validate(array(
            'name' => 'required|string|max:255',
            'avatar' => 'nullable|image',
            'address' => 'nullable|string|max:255',
            'city' => 'nullable|string|max:255',
            'country' => 'nullable|string|max:255',
            'state' => 'nullable|string|max:255',
            'phone' => 'nullable|string|max:255',
            'zipCode' => 'nullable|integer',
            'password' => 'nullable|string|min:8',
        ));

        // Find the model
        $user = User::find($user->id);

        // Upload image
        if ($request->hasFile('avatar')) {
            //get filename with extension
            $filenamewithextension = $request->file('avatar')->getClientOriginalName();

            //get filename without extension
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);

            //get file extension
            $extension = $request->file('avatar')->getClientOriginalExtension();

            //filename to store
            $filenametostore = $filename.'_'.time().'.'.$extension;

            //Upload File
            $request->file('avatar')->storeAs('public/images/profile_images/thumbnail', $filenametostore);

            //Resize image here
            $thumbnailpath = public_path('storage/images/profile_images/thumbnail/'.$filenametostore);
            $img = Image::make($thumbnailpath)->resize(100, 100, function($constraint) {
                $constraint->aspectRatio();
            });
            $img->save($thumbnailpath);

            // Delete previous image from directory
            if ($user->avatar) {
                Storage::delete('public/images/profile_images/thumbnail/'.$user->avatar);
            }

            $user->avatar = $filenametostore;
        }

        if (isset($request->password)) {
            $user->password = Hash::make($request->new_password);
        }

        $user->name = $request->name;
        $user->address = $request->address;
        $user->city = $request->city;
        $user->country = $request->country;
        $user->state = $request->state;
        $user->zipCode = $request->zipCode;
        $user->phone = $request->phone;
        $user->save();

        return redirect()->back()->with('success', 'Client updated successfully.');
    }
}

resources/views/admin/user/user-show.blade.php
@extends('admin.layouts.app')

@section('title')
    User show
@endsection

@section('heading')
    Users show
@endsection

@section('breadcrumb')
    Users show
@endsection

@section('content')
    @if(Session::has('success'))
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {!! html_entity_decode(Session::get('success')) !!}
    </div>
    @endif
    <!-- Row created callback -->
    <div class="row" id="user-page-wrapper">
        <div class="col-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">{{ $user->name }}</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('users') }}" class="btn btn-info"><i class="mdi mdi-step-backward"></i> Back to list</a>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-xl-3">
                            <!-- Nav tabs -->
                            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                <a class="nav-link active" id="v-pills-order-tab" data-toggle="pill" href="#v-pills-order" role="tab" aria-controls="v-pills-order" aria-selected="true">Clients Order</a>
                                <a class="nav-link" id="v-pills-addresses-tab" data-toggle="pill" href="#v-pills-addresses" role="tab" aria-controls="v-pills-addresses" aria-selected="false">Clients addresses</a>
                                <a class="nav-link" id="v-pills-payment-tab" data-toggle="pill" href="#v-pills-payment" role="tab" aria-controls="v-pills-payment" aria-selected="false">Clients payment</a>
                                <a class="nav-link" id="v-pills-invoice-tab" data-toggle="pill" href="#v-pills-invoice" role="tab" aria-controls="v-pills-invoice" aria-selected="false">Clients invoices</a>
                            </div>
                        </div>
                        <div class="col-lg-8 col-xl-9">
                            <div class="tab-content p-4" id="v-pills-tabContent">
                                <div class="tab-pane fade active show" id="v-pills-order" role="tabpanel" aria-labelledby="v-pills-home-tab">
                                    <div class="table-responsive">
                                        <table id="zero_config" class="table table-striped table-hover border display" style="width:100%;">
                                            <thead>
                                            <tr>
                                                <th>Receiver name</th>
                                                <th>Country</th>
                                                <th>State</th>
                                                <th>City</th>
                                                <th>Zip-code</th>
                                                <th>Address</th>
                                                <th>Price</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($user->orders as $order)
                                                <tr>
                                                    <td>{{ $order->receiver_contactname }}</td>
                                                    <td>{{ $order->receiver_country }}</td>
                                                    <td>{{ $order->receiver_province }}</td>
                                                    <td>{{ $order->receiver_town }}</td>
                                                    <td>{{ $order->receiver_postcode }}</td>
                                                    <td>{{ $order->receiver_address }}</td>
                                                    <td>€ {{ $order->price }}</td>
                                                    <td>
                                                        <form action="{{ route('invoices.store')}}" id="invoices-create" method="post">
                                                            @csrf
                                                            <input type="hidden" name="order_id" value="{{ $order->id }}">
                                                        </form>
                                                        <form action="{{ route('orders.destroy', $order->id)}}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="{{ route('orders.show', $order->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                                            <a href="{{ route('orders.edit', $order->id)}}" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i> </a>
                                                            <a href="@if($order->invoice){{ route('invoices.show', $order->id)}}@else javascript:void(0) @endif" @if(!$order->invoice) onclick="event.preventDefault();document.getElementById('invoices-create').submit();" @endif class="btn btn-primary btn-circle"><i class="fas fa-file-alt"></i> </a>
                                                            <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="v-pills-addresses" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                                    <div class="table-responsive">
                                        <table id="zero_config" class="table table-striped table-hover border display" style="width:100%;">
                                            <thead>
                                            <tr>
                                                <th>Phone</th>
                                                <th>Country</th>
                                                <th>State</th>
                                                <th>City</th>
                                                <th>Zip-code</th>
                                                <th>Address</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($user->addresses as $address)
                                                <tr>
                                                    <td>{{ $address->phone }}</td>
                                                    <td>{{ $address->country }}</td>
                                                    <td>{{ $address->state }}</td>
                                                    <td>{{ $address->city }}</td>
                                                    <td>{{ $address->zipCode }}</td>
                                                    <td>{{ $address->address }}</td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="v-pills-payment" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                                    <p> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.</p>
                                    Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.
                                </div>
                                <div class="tab-pane fade" id="v-pills-invoice" role="tabpanel" aria-labelledby="v-pills-invoice-tab">
                                    <div class="table-responsive">
                                        <table id="zero_config" class="table table-striped table-hover border display" style="width: 100%">
                                            <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Order No</th>
                                                <th>Customer Name</th>
                                                <th>Balance</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($user->orders as $order)
                                                @if($order->invoice)
                                                <tr>
                                                    <td>{{ $order->invoice->created_at }}</td>
                                                    <td>{{ $order->id }}</td>
                                                    <td>{{ $order->user->name }}</td>
                                                    <td>€ {{ $order->price }}</td>
                                                    <td>
                                                        <form action="https://www.app.fattura24.com/api/v0.3/GetFile" id="invoices-download" method="post">
                                                            @csrf
                                                            <input type="hidden" name="apiKey" value="{{ env('FATTURA24_API_KEY') }}">
                                                            <input type="hidden" name="docId" value="{{ $order->invoice->docId }}">
                                                        </form>
                                                        <form action="{{ route('invoices.destroy', $order->invoice->id)}}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="{{ route('invoices.show', $order->invoice->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                                            <a href="javascript:void(0)" onclick="event.preventDefault();document.getElementById('invoices-download').submit();" class="btn btn-primary btn-circle"><i class="fas fa-file-pdf"></i> </a>
                                                            <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endif
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/users.blade.php
@extends('admin.layouts.app')

@section('title')
    Users
@endsection

@section('heading')
    Users
@endsection

@section('breadcrumb')
    Users
@endsection

@section('content')
    @if(Session::has('success'))
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {!! html_entity_decode(Session::get('success')) !!}
    </div>
    @endif
    <!-- Row created callback -->
    <div class="row" id="user-page-wrapper">
        <div class="col-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title">Clients</h4>
                        </div>
                        <div class="col-md-2 text-right">

                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-hover border display" style="width:100%;">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Country</th>
                                <th>State</th>
                                <th>City</th>
                                <th>Zip-code</th>
                                <th>Address</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($clients as $client)
                            <tr>
                                <td>{{ $client->name }}</td>
                                <td><img src="{{ asset('storage/images/profile_images/thumbnail/'.$client->avatar) }}" height="100px" width="100px" style="border-radius: 50%"></td>
                                <td>{{ $client->email }}</td>
                                <td>{{ $client->phone }}</td>
                                <td>{{ $client->country }}</td>
                                <td>{{ $client->state }}</td>
                                <td>{{ $client->city }}</td>
                                <td>{{ $client->zipCode }}</td>
                                <td>{{ $client->address }}</td>
                                <td>
                                    <form action="{{ route('users.destroy', $client->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('users.show', $client->id)}}" class="btn btn-info btn-circle"><i class="fa fa-eye"></i> </a>
                                        <a href="{{ route('users.edit', $client->id)}}" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i> </a>
                                        <button type="submit" onclick="return confirm('Are you sure want to delete this data?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection